'use client'

import { useState } from 'react'
import { Sparkles, Loader2, AlertTriangle } from 'lucide-react'
import { api } from '@/lib/api'

interface Props {
  type: 'alert' | 'incident'
  id: string
}

export default function TriageSummary({ type, id }: Props) {
  const [state, setState] = useState<'idle' | 'loading' | 'done' | 'error'>('idle')
  const [summary, setSummary] = useState('')
  const [error, setError] = useState('')

  async function run() {
    setState('loading')
    setError('')
    try {
      const res = await api.triage(type, id)
      setSummary(res.summary)
      setState('done')
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to generate summary')
      setState('error')
    }
  }

  if (state === 'idle') {
    return (
      <button
        onClick={run}
        className="flex items-center gap-2 rounded-lg bg-violet-900/30 px-4 py-2.5 text-sm font-medium text-violet-300 ring-1 ring-violet-700/50 hover:bg-violet-900/50 hover:text-violet-200 transition-all"
      >
        <Sparkles className="h-4 w-4" />
        AI Triage Summary
      </button>
    )
  }

  if (state === 'loading') {
    return (
      <div className="flex items-center gap-2 rounded-lg bg-violet-900/20 px-4 py-2.5 text-sm text-violet-400 ring-1 ring-violet-700/40">
        <Loader2 className="h-4 w-4 animate-spin" />
        Analysing with Claude…
      </div>
    )
  }

  if (state === 'error') {
    return (
      <div className="flex items-start gap-2 rounded-lg bg-red-950/30 px-4 py-3 text-sm text-red-400 ring-1 ring-red-800/40">
        <AlertTriangle className="h-4 w-4 shrink-0 mt-0.5" />
        <span>{error.includes('ANTHROPIC_API_KEY') ? 'Add ANTHROPIC_API_KEY to backend .env to enable AI summaries.' : error}</span>
      </div>
    )
  }

  // Parse bullets — lines starting with 1. 2. 3. or • –
  const lines = summary
    .split('\n')
    .map(l => l.replace(/^[\d]+\.\s*|^[•–-]\s*/, '').trim())
    .filter(Boolean)

  return (
    <div className="rounded-lg bg-violet-950/30 p-4 ring-1 ring-violet-700/40">
      <div className="flex items-center gap-2 mb-3">
        <Sparkles className="h-4 w-4 text-violet-400" />
        <span className="text-xs font-semibold uppercase tracking-wider text-violet-400">AI Triage Summary</span>
        <button
          onClick={() => setState('idle')}
          className="ml-auto text-xs text-violet-600 hover:text-violet-400 transition-colors"
        >
          Regenerate
        </button>
      </div>
      <ol className="space-y-2">
        {lines.map((line, i) => (
          <li key={i} className="flex gap-2.5 text-sm text-slate-300 leading-relaxed">
            <span className="shrink-0 w-5 h-5 rounded-full bg-violet-800/60 text-violet-300 text-[10px] font-bold flex items-center justify-center mt-0.5">
              {i + 1}
            </span>
            {line}
          </li>
        ))}
      </ol>
      <p className="mt-3 text-[10px] text-slate-600">Generated by Claude · Not a substitute for analyst judgement</p>
    </div>
  )
}
