from typing import Any, Protocol


class DataSource(Protocol):
    async def get_secure_score(self) -> dict[str, Any]: ...
    async def get_recommendations(self, severity: str | None = None) -> list[dict]: ...
    async def get_recommendation(self, rec_id: str) -> dict | None: ...
    async def get_alerts(self, status: str | None = None) -> list[dict]: ...
    async def get_alert(self, alert_id: str) -> dict | None: ...
    async def get_vulnerabilities(self) -> list[dict]: ...
    async def get_compliance(self) -> list[dict]: ...
    async def get_resources(self) -> list[dict]: ...
    async def get_resource(self, resource_id: str) -> dict | None: ...
    async def get_signins(self) -> list[dict]: ...
